### ISSUE TITLE
In Java 7+ you can catch multiple exceptions at once

### ISSUE THREAD

**Issue by glynkwei** [Konnoke/ElasticsearchJsonParser#3]
https://github.com/Konnoke/ElasticsearchJsonParser/blob/1fe16780e1872ce0bf6a5e8b639a45a3ec01e1f4/src/elasticsearchjsonparser/ElasticsearchJsonParser.java#L111

**Comment by Konnoke** [comment]
Alternatives in a multi catch cannot work be related by subclassing. JsonGenerationException is a subclass of IOException but you do have a point. JsonGenerationException and JsonMappingException can be combine.
`} catch (JsonGenerationException | JsonMappingException e) {
            e.printStackTrace();
        } catch (IOException e){
            e.printStackTrace();
        }`
