### ISSUE TITLE
shouldn't use absolute paths

### ISSUE THREAD

**Issue by glynkwei** [Konnoke/ElasticsearchJsonParser#4]
https://github.com/Konnoke/ElasticsearchJsonParser/blob/1fe16780e1872ce0bf6a5e8b639a45a3ec01e1f4/src/elasticsearchjsonparser/ElasticsearchJsonParser.java#L37

**Comment by Konnoke** [comment]
1e5504cbdd8bd8a94684be87f6e5e06fffc52ed6
