### ISSUE TITLE
purpose of initializing these variables?

### ISSUE THREAD

**Issue by glynkwei** [Konnoke/ElasticsearchJsonParser#5]
https://github.com/Konnoke/ElasticsearchJsonParser/blob/1fe16780e1872ce0bf6a5e8b639a45a3ec01e1f4/src/elasticsearchjsonparser/ElasticsearchJsonParser.java#L127

**Comment by Konnoke** [comment]
I can see the point of not initializing these variables because the length for each object were used only once.

But then again, you don't know if you'll need to use it again later, so I initialized them for reuse later.
